version: "3.3"
services:
  database:
    image: postgres:13
    container_name: local2_ebac
    restart: always
    ports:
      - "15432:15432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres2